project_id = "bacwlstdjceottxccrap"

[functions.create-professional]
verify_jwt = true

[functions.create-receptionist]
verify_jwt = true

[functions.list-receptionists]
verify_jwt = true

[functions.delete-receptionist]
verify_jwt = true
